<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.2" tiledversion="1.3.1" name="Objects" tilewidth="32" tileheight="32" tilecount="64" columns="8">
 <image source="../textures/entity_32x32.png" width="256" height="256"/>
 <tile id="0" type="PACMAN"/>
 <tile id="1" type="PACMAN"/>
 <tile id="2" type="PACMAN"/>
 <tile id="3" type="PACMAN"/>
 <tile id="4" type="PACGUM2"/>
 <tile id="5" type="PACGUM1"/>
 <tile id="6" type="PACGUM3"/>
 <tile id="8" type="PACMAN"/>
 <tile id="9" type="PACMAN"/>
 <tile id="10" type="PACMAN"/>
 <tile id="11" type="PACMAN"/>
 <tile id="12" type="ITEM"/>
 <tile id="13" type="ITEM"/>
 <tile id="14" type="ITEM"/>
 <tile id="15" type="ITEM"/>
 <tile id="16" type="PACMAN"/>
 <tile id="17" type="PACMAN"/>
 <tile id="18" type="PACMAN"/>
 <tile id="19" type="PACMAN"/>
 <tile id="24" type="PACMAN"/>
 <tile id="25" type="PACMAN"/>
 <tile id="26" type="PACMAN"/>
 <tile id="27" type="PACMAN"/>
 <tile id="30" type="GHOST"/>
 <tile id="31" type="GHOST"/>
 <tile id="32" type="GHOST"/>
 <tile id="33" type="GHOST"/>
 <tile id="34" type="GHOST"/>
 <tile id="35" type="GHOST"/>
 <tile id="36" type="GHOST"/>
 <tile id="37" type="GHOST"/>
 <tile id="38" type="GHOST"/>
 <tile id="39" type="GHOST"/>
 <tile id="40" type="GHOST"/>
 <tile id="41" type="GHOST"/>
 <tile id="42" type="GHOST"/>
 <tile id="43" type="GHOST"/>
 <tile id="44" type="GHOST"/>
 <tile id="45" type="GHOST"/>
 <tile id="46" type="GHOST"/>
 <tile id="47" type="GHOST"/>
 <tile id="48" type="GHOST"/>
 <tile id="49" type="GHOST"/>
 <tile id="50" type="GHOST"/>
 <tile id="51" type="GHOST"/>
 <tile id="52" type="GHOST"/>
 <tile id="53" type="GHOST"/>
 <tile id="54" type="GHOST"/>
 <tile id="55" type="GHOST"/>
 <tile id="56" type="GHOST"/>
 <tile id="57" type="GHOST"/>
 <tile id="58" type="GHOST"/>
 <tile id="59" type="GHOST"/>
 <tile id="60" type="GHOST"/>
 <tile id="61" type="GHOST"/>
 <tile id="62" type="GHOST"/>
 <tile id="63" type="GHOST"/>
</tileset>
