<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.2" tiledversion="1.3.1" name="Tileset" tilewidth="32" tileheight="32" tilecount="140" columns="14">
 <image source="../textures/tiles.png" width="448" height="320"/>
 <tile id="5" type="WALL"/>
 <tile id="8" type="WALL"/>
 <tile id="9" type="WALL"/>
 <tile id="10" type="WALL"/>
 <tile id="11" type="WALL"/>
 <tile id="12" type="WALL"/>
 <tile id="19" type="WALL"/>
 <tile id="22" type="WALL"/>
 <tile id="23" type="WALL"/>
 <tile id="24" type="WALL"/>
 <tile id="25" type="WALL"/>
 <tile id="26" type="WALL"/>
 <tile id="33" type="WALL"/>
 <tile id="36" type="WALL"/>
 <tile id="37" type="WALL"/>
 <tile id="38" type="WALL"/>
 <tile id="39" type="WALL"/>
 <tile id="40" type="WALL"/>
 <tile id="47" type="WALL"/>
 <tile id="50" type="WALL"/>
 <tile id="51" type="WALL"/>
 <tile id="52" type="WALL"/>
 <tile id="53" type="WALL"/>
 <tile id="54" type="WALL"/>
 <tile id="55" type="WALL"/>
 <tile id="61" type="WALL"/>
 <tile id="64" type="WALL"/>
 <tile id="65" type="WALL"/>
 <tile id="66" type="WALL"/>
 <tile id="67" type="WALL"/>
 <tile id="68" type="WALL"/>
 <tile id="69" type="WALL"/>
 <tile id="75" type="WALL"/>
 <tile id="78" type="WALL"/>
 <tile id="79" type="WALL"/>
 <tile id="80" type="WALL"/>
 <tile id="81" type="WALL"/>
 <tile id="82" type="WALL"/>
 <tile id="89" type="WALL"/>
 <tile id="92" type="WALL"/>
 <tile id="93" type="WALL"/>
 <tile id="94" type="WALL"/>
 <tile id="95" type="WALL"/>
 <tile id="96" type="WALL"/>
 <tile id="103" type="WALL"/>
 <tile id="106" type="WALL"/>
 <tile id="107" type="WALL"/>
 <tile id="108" type="WALL"/>
 <tile id="109" type="WALL"/>
 <tile id="110" type="WALL"/>
 <tile id="117" type="WALL"/>
 <tile id="120" type="WALL"/>
 <tile id="121" type="WALL"/>
 <tile id="122" type="WALL"/>
 <tile id="123" type="WALL"/>
 <tile id="124" type="WALL"/>
 <tile id="131" type="WALL"/>
 <tile id="134" type="WALL"/>
 <tile id="135" type="WALL"/>
 <tile id="136" type="WALL"/>
 <tile id="137" type="WALL"/>
 <tile id="138" type="WALL"/>
</tileset>
